ALTER TABLE "Paper" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'Pending';
ALTER TABLE "Paper" ADD COLUMN IF NOT EXISTS "researcherId" TEXT;
ALTER TABLE "Paper" ADD COLUMN IF NOT EXISTS "researcherName" TEXT;
